### ISSUE TITLE
rename.py is overwriting itself

### ISSUE THREAD

**Issue by sutukh19** [MarvinJWendt/Rename-Files-To-Hash#1]
I would modify the following lines as such to fix the issue:
30     if not file == "rename.py":
     31         if not file == "random.bat":

**Comment by MarvinJWendt** [comment]
Oh that´s right ._.
I always name this file !rename.py to keep it at the top of the filelist, but as it seems I uploaded it without the exclamation mark..
Thank you for pointing this out 👍
